export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = "DELETE_FACILITIES";
export const EDIT_FACILITIES = "EDIT_FACILITIES";
export const LODING_FACILITIES = "LODING_FACILITIES";
export const GET_FACILITIES = "GET_FACILITIES"


export const GET_PRODUCT = "GET_PRODUCT"   
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const LODING_PRODUCT = "LODING_PRODUCT";
export const ERROR_PRODUCT = "ERROR_PRODUCT";

export const GET_REVIEW = "GET_REVIEW"   
export const ADD_REVIEW = "ADD_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";
export const LODING_REVIEW = "LODING_REVIEW";
export const ERROR_REVIEW = "ERROR_REVIEW";
