export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = "DELETE_FACILITIES";
export const EDIT_FACILITIES = "EDIT_FACILITIES";
export const LODING_FACILITIES = "LODING_FACILITIES";
export const GET_FACILITIES = "GET_FACILITIES"


export const GET_PRODUCT = "GET_PRODUCT"   
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const LODING_PRODUCT = "LODING_PRODUCT";