export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = "DELETE_FACILITIES";
export const EDIT_FACILITIES = "EDIT_FACILITIES";
export const LODING_FACILITIES = "LODING_FACILITIES";
export const GET_FACILITIES = "GET_FACILITIES"